// <auto-generated />
namespace fftoolkit.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Makingparametersrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Makingparametersrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201806160528168_Making parameters required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
