// <auto-generated />
namespace fftoolkit.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingleaguetodraft : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingleaguetodraft));
        
        string IMigrationMetadata.Id
        {
            get { return "201908181110048_adding league to draft"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
